FILES=main.c ex00/ft_ft.c ex01/ft_ultimate_ft.c ex02/ft_swap.c ex03/ft_div_mod.c ex04/ft_ultimate_div_mod.c ex05/ft_putstr.c ex06/ft_strlen.c ex07/ft_strrev.c ex08/ft_atoi.c ex09/ft_sort_integer_table.c

hellomake: $(FILES)
	gcc -o a $(FILES) -Wall -Wextra -Werror
