FILES=main.c ex00/ft_strdup.c ex01/ft_range.c ex02/ft_ultimate_range.c ex03/ft_concat_params.c ex04/ft_split_whitespaces.c ex05/ft_print_words_tables.c ex06/ft_convert_base.c ex07/ft_split.c

hellomake: $(FILES)
	gcc -o a $(FILES) -Wall -Wextra -Werror
	#gcc -o a $(FILES)
